<%@ page language="java" pageEncoding="utf-8"%>

<!-- basic scripts -->

<!--[if !IE]> -->

<script type="text/javascript">
	window.jQuery || document.write("<script src='resource/ace/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
</script>

<!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='resource/ace/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
	if("ontouchend" in document) document.write("<script src=resource/ace/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>
<script src="resource/ace/js/bootstrap.min.js"></script>
<script src="resource/ace/js/typeahead-bs2.min.js"></script>

<!-- page specific plugin scripts -->
<!-- jquery-ui custom -->
<script src="resource/ace/js/jquery-ui-1.10.4.custom.min.js"></script>

<!-- jquery-ui-datepicker 中文本地化 -->
<script src="resource/ace/js/jquery.ui.datepicker-zh-TW.js"  charset="UTF-8"></script>

<!-- bootstrap bootbox对话框 -->
<script src="resource/ace/js/bootbox.min.js"></script>

<!-- spinner -->
<script src="resource/ace/js/fuelux/fuelux.spinner.min.js"></script>

<!-- 日期控件 -->
<!-- <script src="resource/ace/js/date-time/bootstrap-datepicker.min.js"></script> -->
<!-- <script src="resource/ace/js/date-time/locales/bootstrap-datepicker.zh-CN.js" charset="UTF-8"></script> -->

<!-- gritter -->
<script src="resource/ace/js/jquery.gritter.min.js"></script>

<!-- bootbox -->
<script src="resource/ace/js/bootbox.min.js"></script>

<!-- jqgrid -->
<script src="resource/ace/js/jqGrid/jquery.jqGrid.min.js"></script>
<script src="resource/ace/js/jqGrid/i18n/grid.locale-cn.js"></script>

<!-- 自动补全 -->
<script src="resource/ace/js/chosen.jquery.min.js"></script>

<!-- jquery-form -->
<script src="resource/inesa/js/plugin/jquery-form/jquery.form.js"></script>

<!-- jquery-validate -->
<script src="resource/ace/js/jquery.validate.min.js"></script>
<script src="resource/ace/js/additional-methods.min.js"></script>


<!-- ace scripts -->
<script src="resource/ace/js/ace-elements.min.js"></script>
<script src="resource/ace/js/ace.min.js"></script>

<!-- base64 -->
<script src="resource/inesa/js/plugin/base64/base64.min.js"></script>

<!-- underscore -->
<!-- 
<script src="resource/inesa/js/plugin/underscore.min.js"></script>
 -->


<!-- ace settings handler -->

<script src="resource/ace/js/ace-extra.min.js"></script>

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

<!--[if lt IE 9]>
<script src="resource/ace/js/html5shiv.js"></script>
<script src="resource/ace/js/respond.min.js"></script>
<![endif]-->


<!-- browser msie issue fix -->
<script src="resource/inesa/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>

<!-- mustache.js -->
<script src="resource/inesa/js/plugin/mustache/mustache.js"></script>

<!-- hiAlert -->
<link rel="stylesheet" href="resource/inesa/js/plugin/hiAlert/css/alert.css" />
<script src="resource/inesa/js/plugin/hiAlert/jquery.alert.js"></script>

<!-- bootstrap-switch -->
<link rel="stylesheet" href="resource/inesa/js/plugin/bootstrap-switch-master/css/bootstrap-switch.min.css" />
<script src="resource/inesa/js/plugin/bootstrap-switch-master/js/bootstrap-switch.min.js"></script>

<!-- fileupload -->
<script src="resource/inesa/js/plugin/fileupload/jquery.ui.widget.js"></script>
<script src="resource/inesa/js/plugin/fileupload/jquery.iframe-transport.js"></script>
<script src="resource/inesa/js/plugin/fileupload/jquery.fileupload.js"></script>

<!-- app -->
<script src="resource/inesa/js/app.js"></script>

<!-- common -->
<script src="resource/inesa/js/common.js"></script>

<!-- modal -->
<script src="resource/inesa/js/modal.js"></script>

<!-- file -->
<script src="resource/inesa/js/file.js"></script>

<!-- bootstrapmessager -->
<%--<script src="wf/resource/inesa/js/bootstrap.messager.js"></script>--%>

<!-- ztree -->
<%--<script type="text/javascript" src="wf/gooflow/PropertyBox/js/jquery.ztree.core-3.5.js"></script>--%>
<%--<script type="text/javascript" src="wf/gooflow/PropertyBox/js/jquery.ztree.excheck-3.5.js"></script>--%>
<%--<script type="text/javascript" src="wf/gooflow/PropertyBox/js/jquery.ztree.exedit-3.5.js"></script>	--%>
<%--<script type="text/javascript" src="resource/inesa/js/choose-tree.js"></script>--%>








